<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="17" failed="1" total="20" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24766" started-at="2016-05-13T13:36:49Z" finished-at="2016-05-13T13:37:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24766" started-at="2016-05-13T13:36:49Z" finished-at="2016-05-13T13:37:14Z">
      <class name="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="setup" is-config="true" duration-ms="7522" started-at="2016-05-13T14:36:49Z" finished-at="2016-05-13T14:36:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="goToHomepage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="goToHomepage" duration-ms="8814" started-at="2016-05-13T14:36:57Z" finished-at="2016-05-13T14:37:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToHomepage -->
        <test-method status="PASS" signature="institutionLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="institutionLogin" duration-ms="7465" started-at="2016-05-13T14:37:06Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.goToHomepage" finished-at="2016-05-13T14:37:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- institutionLogin -->
        <test-method status="FAIL" signature="enterInstitutionLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="enterInstitutionLoginDetails" duration-ms="4" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.institutionLogin" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Unipupil.TestFramework.pageObjects.LoginPage.enterUsername(LoginPage.java:50)
	at Unipupil.TestFramework.pageObjects.LoginPage.unipupilLogin(LoginPage.java:77)
	at Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.enterInstitutionLoginDetails(BuyCourseAdditionalFeesFirefoxTest.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterInstitutionLoginDetails -->
        <test-method status="SKIP" signature="getCourseList()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="getCourseList" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.enterInstitutionLoginDetails" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.getCourseList()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.getCourseList()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCourseList -->
        <test-method status="SKIP" signature="goToCourseEditPage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="goToCourseEditPage" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.getCourseList" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.goToCourseEditPage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.goToCourseEditPage()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToCourseEditPage -->
        <test-method status="SKIP" signature="getCourseFees()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="getCourseFees" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.goToCourseEditPage" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.getCourseFees()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.getCourseFees()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCourseFees -->
        <test-method status="SKIP" signature="institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="institutionLogout" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.getCourseFees" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.institutionLogout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- institutionLogout -->
        <test-method status="SKIP" signature="studentLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="studentLogin" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.institutionLogout" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.studentLogin()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- studentLogin -->
        <test-method status="SKIP" signature="enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="enterStudentLoginDetails" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.studentLogin" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.enterStudentLoginDetails()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterStudentLoginDetails -->
        <test-method status="SKIP" signature="findInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="findInstitution" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.enterStudentLoginDetails" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.findInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findInstitution -->
        <test-method status="SKIP" signature="selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="selectInstitution" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.findInstitution" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.selectInstitution()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectInstitution -->
        <test-method status="SKIP" signature="selectCourse()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="selectCourse" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.selectInstitution" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.selectCourse()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectCourse -->
        <test-method status="SKIP" signature="addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="addCourseToCart" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.selectCourse" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.addCourseToCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCourseToCart -->
        <test-method status="SKIP" signature="viewCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="viewCart" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.addCourseToCart" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.viewCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.viewCart()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewCart -->
        <test-method status="SKIP" signature="checkout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="checkout" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.viewCart" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.checkout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkout()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkout -->
        <test-method status="SKIP" signature="reviewOrder()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="reviewOrder" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.checkout" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.reviewOrder()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.reviewOrder()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reviewOrder -->
        <test-method status="SKIP" signature="payForProduct()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="payForProduct" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.reviewOrder" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.payForProduct()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.payForProduct()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- payForProduct -->
        <test-method status="SKIP" signature="checkOrderStatus()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="checkOrderStatus" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.payForProduct" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.checkOrderStatus()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkOrderStatus()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOrderStatus -->
        <test-method status="SKIP" signature="checkStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="checkStudentAccount" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.checkOrderStatus" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.checkStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.checkStudentAccount()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStudentAccount -->
        <test-method status="SKIP" signature="logOut()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="logOut" duration-ms="0" started-at="2016-05-13T14:37:13Z" depends-on-methods="Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest.checkStudentAccount" finished-at="2016-05-13T14:37:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BuyCourseAdditionalFeesFirefoxTest.logOut()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BuyCourseAdditionalFeesFirefoxTest.logOut()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method status="PASS" signature="shutdown()[pri:0, instance:Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest@13fee20c]" name="shutdown" is-config="true" duration-ms="866" started-at="2016-05-13T14:37:13Z" finished-at="2016-05-13T14:37:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutdown -->
      </class> <!-- Unipupil.UniMavenTests.BuyCourseAdditionalFeesFirefoxTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
